# Generated by Django 2.0.13 on 2022-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.IntegerField()),
                ('f2', models.CharField(max_length=50)),
                ('f3', models.CharField(max_length=50)),
            ],
        ),
    ]
